cache:
    directories:
        - node_modules
        - client/node_modules
dist: trusty
env: NODE_ENV=ci PORT=3000
install:
    - npm install
    - npm run build
language: node_js
node_js:
    - '8'
script:
    - nohup npm run start &
    - sleep 3
    - npm run test
services:
    - mongodb
notifications:
    slack: chingubetavoyage:3PhnaQaT7wzLK4TmBiOJycD0
