--- 
cache: 
  directories: 
    - node_modules
    - client/node_modules
deploy: 
  api_key: 
    secure: Bxn430Ua9tAb1L35CFgwZgMp+WUOTbhWD0G21IgvEnjiVogbtLbw5ZT5vVSh1+TS77o2TyJQb7THIKGTEaghs5WdKhfhYv0vgmFrgUV4NxLXFDzXHV3eqWnegRr/8KtTr+7dzGZ/h4KK2qKE/czG56BOPs2Y3nfjP8LglWMPaZnxJE+btMyB7ckv2nfQ/5enbFS95Tmp4xK8kgh21isYq8Unlw76TRWXGRfF8PWzf4MXhCEWsSkZt65ubeGstH86Igxq0OrY4dy1OkoEuJKSISE+TvOi3qa6sK8eBEceivMbVvBnkOduieZzb7xQhteQSHt7Yslxe3ViKLDJ4oty39garrptLeQ0kO1x6q3UxV9r3vxEQcTCRFtHB9L/bDrsIcK8Ku3atgiwm7o3BH8zqJEZiL7EJgwSlAYd23YOtx4PG4uZ4te2P4sUKYwgMv8XQm+vJtGarJ2hmkRW+Q1vXppGFehcBh1Gx/mdq9iWtI2EdRhR0P37aPWs+ns2pIn0Me4RWx97kEVsS/8XToibRnP81NTlqlTVuM8avhBTy8g3elnSYRg/v3thWF/2XP7BOIyEEJfV2LiCoYJyGmQaSiNouN7ybSKpJjEVhIwPXoPJAo6W+lmHmegmHAnfwXISVwcFETCTXq13YXltKaaVz9JXDk8koOWQFb0ScTHPpkQ=
  app: chingu-habit-tracker
  provider: heroku
dist: trusty
env: "NODE_ENV=ci PORT=3000"
install: 
  - "npm install"
  - "npm run build"
language: node_js
node_js: 
  - "8"
notifications: 
  email: false
  slack: "chingubetavoyage:3PhnaQaT7wzLK4TmBiOJycD0"
script: 
  - "nohup npm run start &"
  - "sleep 3"
  - "npm run test"
services: 
  - mongodb
